
// Objective-C API for talking to the following Go packages
//
//	v2ray.com/core
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Core_FRAMEWORK_H__
#define __Core_FRAMEWORK_H__

#include "V2RayCore.objc.h"
#include "Universe.objc.h"

#endif
